### ISSUE TITLE
[Suggestion] Robot type

### ISSUE THREAD

**Issue by baggepinnen** [baggepinnen/Robotlib.jl#14]
Instead of
```julia
dh = DHYuMi()
fkine, ikine, jacobian = get_kinematic_functions("yumileft")
```

we could introduce an `AbstractRobot` type and let
```julia
struct YuMi <: AbstractRobot
    fkine::Function
    ikine::Function
    jacobian::Function
    dh::DH
    ...
end
```
for which an OO like syntax could be used, e.g.,
```julia
yumi = YuMi()
T = yumi.fkine(q)
J = yumi.jacobian(q)
```

This would make it easier to work with many robots at the same time and the user would only need to remember how to create a robot (`yumi = YuMi()`), as opposed to remember every individual function related to kinematics etc.
Input? @martin-kar

**Comment by martin-kar** [comment]
Sounds great, Im in favor!
