### ISSUE TITLE
isskew should handle small numerical deviations

### ISSUE THREAD

**Issue by andreasstolt** [baggepinnen/Robotlib.jl#33]
The following matrix is in the current implementation not considered to be skew symmetric:

```
S = [
    3.469446951953614e-17 0.01413101017790172 0.5555528457618361
    -0.014131010177901714 1.734723475976807e-17 0.06871266098996705
    -0.5555528457618361 -0.06871266098996702 2.7755575615628914e-17
]
```
Either isskew should accept small numerical deviations, or it should be possible to override the isskew check when calling skewcoords.

**Comment by andreasstolt** [comment]
Would something like

```
norm(S - S') < tol
```

for some small tolerance be a better condition to check?

**Comment by baggepinnen** [comment]
Decided that `isskew` is strict, similar to `issymmetric` and provided `skewify(R)` that the user can use to explicitly make a matrix skew symmetrc.
